"""keep_spec — the keep/v1 AgentSpec envelope (contract: contracts/agent-spec.md).

Complete stage-2 schema: a field home for all 18 agent-level decisions of
ADR 0003 (see keep_spec.decision_coverage). Everything beyond the walking
skeleton's subset is optional or defaulted — additive under the frozen
envelope rules.
"""

from keep_spec.decision_coverage import DECISIONS, Decision, assert_full_coverage
from keep_spec.egress import egress_entry_allows, match_allowlist
from keep_spec.models import (
    AgentSpec,
    AllowlistEntry,
    AnthropicProviderConfig,
    Approval,
    AuditConfig,
    Channel,
    ChannelVerification,
    DevHttpChannel,
    DiscordChannel,
    EventTrigger,
    FactsMemory,
    Gateway,
    GatewayAllowlist,
    HealthConfig,
    History,
    HttpTransport,
    LayeredHistory,
    LayeredMemory,
    LocalTransport,
    McpServer,
    McpTransport,
    Memory,
    MemoryStructure,
    MessageTrigger,
    Metadata,
    ModelBudgets,
    Models,
    ModelTier,
    Observability,
    OllamaProviderConfig,
    OpenAIProviderConfig,
    Persistence,
    Persona,
    RetrievalHistory,
    Sandbox,
    ScheduleTrigger,
    Sessions,
    SkillPack,
    SlackChannel,
    SlidingWindowHistory,
    SmsChannel,
    SpecSections,
    StaticProviderConfig,
    StdioTransport,
    SummarizationHistory,
    ToolGrant,
    Trigger,
    Triggers,
    WebexChannel,
    dump_spec_data,
    dump_spec_yaml,
    load_spec,
    validate_spec_data,
)
from keep_spec.reference_export import reference_markdown
from keep_spec.schema_export import export_schema

__all__ = [
    "DECISIONS",
    "AgentSpec",
    "AllowlistEntry",
    "AnthropicProviderConfig",
    "Approval",
    "AuditConfig",
    "Channel",
    "ChannelVerification",
    "Decision",
    "DevHttpChannel",
    "DiscordChannel",
    "EventTrigger",
    "FactsMemory",
    "Gateway",
    "GatewayAllowlist",
    "HealthConfig",
    "History",
    "HttpTransport",
    "LayeredHistory",
    "LayeredMemory",
    "LocalTransport",
    "McpServer",
    "McpTransport",
    "Memory",
    "MemoryStructure",
    "MessageTrigger",
    "Metadata",
    "ModelBudgets",
    "ModelTier",
    "Models",
    "Observability",
    "OllamaProviderConfig",
    "OpenAIProviderConfig",
    "Persistence",
    "Persona",
    "RetrievalHistory",
    "Sandbox",
    "ScheduleTrigger",
    "Sessions",
    "SkillPack",
    "SlackChannel",
    "SlidingWindowHistory",
    "SmsChannel",
    "SpecSections",
    "StaticProviderConfig",
    "StdioTransport",
    "SummarizationHistory",
    "ToolGrant",
    "Trigger",
    "Triggers",
    "WebexChannel",
    "assert_full_coverage",
    "dump_spec_data",
    "dump_spec_yaml",
    "egress_entry_allows",
    "export_schema",
    "load_spec",
    "match_allowlist",
    "reference_markdown",
    "validate_spec_data",
]
