"""Egress-proxy image bake path — `keep-build build-proxy`.

The proxy ships as its OWN image (`ghcr.io/seanerama/agent-keep-egress-proxy`)
so the choke point observes the agent from OUTSIDE the agent's image (contract
egress-observation v1, ADR 0002). Unlike the agent bake path this one is
spec-INDEPENDENT: one generic proxy image serves every agent, because the
proxy is configured at RUN time by mounting the same spec.yaml the agent image
was baked from (read-only at /etc/agent-keep/spec.yaml — see the keep_egress
package docstring). The image therefore ships exactly two packages: keep_spec
(the validator + the one egress matcher) and keep_egress (the proxy) — never
agent_runtime, never a spec copy.

Same build discipline as the agent path: digest-pinned base (shared
composer.BASE_IMAGE), deps pinned to the workspace's resolved versions,
non-root uid 10001, clean-then-write context reconciliation.
"""

import shutil
from importlib.metadata import version
from pathlib import Path

import keep_egress
import keep_spec
from keep_build.composer import BASE_IMAGE

#: The proxy image identity (extends the ADR 0001 naming convention).
PROXY_IMAGE = "ghcr.io/seanerama/agent-keep-egress-proxy"

#: Runtime deps of the proxy image (keep_spec's own deps; the proxy itself is
#: stdlib-only asyncio), pinned to the workspace's resolved versions.
PROXY_RUNTIME_DEPENDENCIES = ("pydantic", "pyyaml")

#: Context-root paths this bake path generates and therefore OWNS (same
#: reconciliation rule as composer.OWNED_CONTEXT_PATHS).
PROXY_OWNED_CONTEXT_PATHS = ("Dockerfile", "keep_spec", "keep_egress")

#: Default proxy listen port baked into EXPOSE (runtime-overridable via
#: KEEP_EGRESS_PORT; the port is never published on the host — the proxy is
#: reachable only on the paired private container network).
PROXY_PORT = 3128


def proxy_dockerfile() -> str:
    pins = " ".join(f'"{name}=={version(name)}"' for name in PROXY_RUNTIME_DEPENDENCIES)
    return f"""\
# Generated by keep_build for the egress observation proxy (contract
# egress-observation v1, ADR 0002). Spec-independent: the allowlist arrives at
# RUN time as the mounted spec.yaml (KEEP_SPEC_PATH), the same source of truth
# build-time cross-validation uses — the proxy never has its own list.
# Base image pinned by digest: see keep_build.composer.BASE_IMAGE.
FROM {BASE_IMAGE}

RUN pip install --no-cache-dir {pins}

# Non-root runtime user; the proxy's own audit file lives under
# /var/lib/agent-keep (egress-audit.jsonl — separate from the worker's
# audit.jsonl, no write collision); /etc/agent-keep is the read-only spec
# mount point.
RUN useradd --create-home --uid 10001 egress \\
    && mkdir -p /var/lib/agent-keep /etc/agent-keep \\
    && chown egress:egress /var/lib/agent-keep

WORKDIR /app
COPY keep_spec/ /app/keep_spec/
COPY keep_egress/ /app/keep_egress/

ENV PYTHONPATH=/app \\
    PYTHONUNBUFFERED=1

USER egress
EXPOSE {PROXY_PORT}
CMD ["python", "-m", "keep_egress.runner"]
"""


def emit_proxy_build_context(context_dir: Path) -> None:
    """Write the Dockerfile + keep_spec + keep_egress sources into
    `context_dir` (clean-then-write on the owned paths, like the agent path)."""
    context_dir.mkdir(parents=True, exist_ok=True)
    for name in PROXY_OWNED_CONTEXT_PATHS:
        target = context_dir / name
        if target.is_dir() and not target.is_symlink():
            shutil.rmtree(target)
        elif target.exists() or target.is_symlink():
            target.unlink()

    (context_dir / "Dockerfile").write_text(proxy_dockerfile(), encoding="utf-8")
    for src in (Path(keep_spec.__file__).parent, Path(keep_egress.__file__).parent):
        shutil.copytree(
            src,
            context_dir / src.name,
            ignore=shutil.ignore_patterns("__pycache__"),
            dirs_exist_ok=True,
        )
